# Personal OCR priority configuration — not tracked in git
# Copy this file to ocr_priority_config.py and edit to match your library.

BOOKS_DIR = "/home/youruser/Books"

# Books to OCR first — matched case-insensitively against filename
TIER1_KEYWORDS = [
    "russolo",
    "rosenblueth",
    "edvac",
    "cybernetics",
    "ecological approach",
    "notes on the synthesis of form",
    "languages of art",
    "inquiries into truth",
    "simondon",
    "vampyroteuthis",
    "pandora",
    "song books",
    "cage silence",
    "die reihe",
    "xenakis",
    "kagel",
    "nono",
    "boulez",
    "traite de l'orchestration",
    "traité de l'orchestration",
    "new musical resources",
    "harmony book",
    "tuning, timbre",
    "microsound",
    "technology of computer music",
    "elements of computer music",
    "origins of order",
    "course in general linguistics",
    "tesniere",
    "tesnière",
    "bertin",
    "metaphors on vision",
    "on weaving",
    "partch",
    "mindstorms",
    "deep learning with python",
    "concrete mathematics",
    "thinking in postscript",
    "audible past",
    "cracked media",
    "cinema by other means",
    "composing electronic music",
    "sound poetry",
    "wireless imagination",
    "composing with tape",
    "african fractals",
    "emergence-from-chaos",
    "theory of recursive function",
    "giant brains",
    "studies in the way of words",
    "readings in zoosemiotics",
    "cowell",
    "designing sound",
    "persichetti",
    "bailey",
    "berlioz",
    "piston",
    "oxford history of music",
    "american minimal music",
]

# Books to skip even if they match TIER1_KEYWORDS (e.g. replacing with epub)
SKIP_KEYWORDS = ["kagel", "cybernetics", "at home in the universe"]
